### PR TITLE
Support PHPUnit 9.x

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Hah not this easy

> OckCyp\CoversValidator\Tests\Command\ValidateCommandTest::testPrintsConfigFileUsed
> 
> Error: Class 'PHPUnit\Util\Configuration' not found
> 
> /home/travis/build/oradwell/covers-validator/src/Loader/ConfigLoader.php:17
> 
> /home/travis/build/oradwell/covers-validator/src/Handler/InputHandler.php:23
> 
> /home/travis/build/oradwell/covers-validator/src/Command/ValidateCommand.php:52
> 
> /home/travis/build/oradwell/covers-validator/vendor/symfony/console/Command/Command.php:255
> 
> /home/travis/build/oradwell/covers-validator/vendor/symfony/console/Tester/CommandTester.php:76
> 
> /home/travis/build/oradwell/covers-validator/tests/Command/ValidateCommandTest.php:37

https://travis-ci.org/github/oradwell/covers-validator/jobs/663728817

**Comment by oradwell** [comment]
@JeroenDeDauw thanks for opening this PR. sorry I've completely missed this. I'll take a look this week

**Comment by oradwell** [comment]
@JeroenDeDauw I've done some work on this last night. it seems harder than I imagined. they've completely changed Configuration classes. I'm having trouble obtaining the list of tests

**Comment by JeroenDeDauw** [comment]
:tada: 

You did all the work, no need to credit me!

**Comment by oradwell** [comment]
@JeroenDeDauw you created the PR and changed `composer.json`. I think that's enough for getting some credit. I didn't even know PHPUnit 9 was released

**Pull request merged**
